#! /bin/sh

xrdb ~/.Xresources

pgrep -x sxhkd || sxhkd &
pgrep -x polybar || polybar -r &
pgrep -x urxvtd || urxvtd -f &

if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
    # 2 monitor setup
	xrandr --output eDP-1 --mode 1366x768 --left-of HDMI-1
	xrandr --output HDMI-1 --mode 1680x1050 --primary

	bspc monitor HDMI-1 -d 3 4
	bspc monitor eDP-1 -d 1 2
else
    # 1 monitor setup
	xrandr --output eDP-1 --mode 1366x768 --primary \
		--output HDMI-1 --off

	bspc monitor eDP-1 -d 1 2 3 4
fi

bspc config border_width 3
bspc config window_gap 6

bspc config focus_follows_pointer false
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config honor_size_hints false
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on

COLOR0="#2d353b"
COLOR1="#d699b6"
COLOR2="#748478"

bspc config normal_border_color $COLOR2
bspc config focused_border_color $COLOR1
bspc config active_border_color $COLOR1
bspc config presel_feedback_color $COLOR0

bspc config top_padding 16
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

#feh --bg-center "/home/ana/.config/bspwm/wall.png" --image-bg $COLOR0
hsetroot -solid $COLOR0

setxkbmap -model abnt2 -layout br

